version: "3.8"
services:
  db:
    image: postgres
    container_name: typoteka-nest-postgres
    restart: always
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  adminer:
    image: adminer
    container_name: typoteka-nest-adminer
    restart: always
    ports:
      - "${ADMINER_PORT}:8080"
